package com.saberrr.openchina.bean;

import com.thoughtworks.xstream.annotations.XStreamAlias;

/**
 * Created by Saberrr on 2017-04-06.
 */
@XStreamAlias("oschina")
public class UpdateInfo {
    /**
     * <oschina>
     * <update>
     * <wp7>1.4</wp7>
     * <ios>v3.7.0 (1606131024)</ios>
     * <android>
     * <versionCode>283</versionCode>
     * <versionName>v2.8.3(1703281011)</versionName>
     * <downloadUrl>
     * https://www.oschina.net/uploads/osc-android-v2.8.3-release.apk
     * </downloadUrl>
     * <updateLog>
     * <![CDATA[
     * v2.8.3 新版提示 <br/>1、新增「官网人员」标识，再也不会被假冒红薯绿薯紫薯什么的欺骗了~ 2、修复上版本中重复点击刷新数据的问题~ <br><br>大小：14.1M
     * ]]>
     * </updateLog>
     * <coverUpdate>false</coverUpdate>
     * <coverStartDate>2014-03-05</coverStartDate>
     * <coverEndDate>2014-03-05</coverEndDate>
     * <coverURL/>
     * </android>
     * </update>
     * </oschina>
     * <!--
     * Generated by OsChina.NET (init:0[ms],page:1[ms],ip:101.81.195.207)
     * -->
     */
    @XStreamAlias("update")
    public class Update {
        public String wp7;
        public String ios;
        @XStreamAlias("android")
        public class Android {
            public String versionCode;
            public String versionName;
            public String downloadUrl;
            public String updateLog;
            public String coverUpdate;
        }
    }



}
